
version: '2'
services:

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl

  nexus:
    image: sonatype/docker-nexus3
    container_name: nexus
    hostname: nexus
    restart: always
    ports:
      - "8081:8081" # for GUI
      - "8082:8082" # for docker-int registry
      - "8083:8083" # for docker-group registry
      - "18443:18443"
    volumes:
      - /opt/nexus-data:/nexus-data
    links:
      - nginx

  jenkins:
    image: jenkins
    container_name: jenkins
    restart: always
    user: root
    environment:
  #    - JAVA_OPTS=-Xmx512M
      - JENKINS_OPTS=--httpPort=8080
    ports:
      - "50000:50000"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /var/lib/jenkins:/var/jenkins_home
      - /tmp:/tmp
    links:
      - nginx

  tomcat:
    image: flyer8/tomcat8
    container_name: tomcat
    restart: always
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
    ports:
      - "8888:8080"
      - "8009:8009"
#    volumes:
#      - /opt/tomcat/webapps:/usr/local/tomcat/webapps
    links:
      - nginx
